"""Tracing constants."""

TRACE_REQUEST_TYPE_DIAGNOSIS = "diagnosis"
TRACE_REQUEST_TYPE_GENERAL_CHAT = "general_chat"

TRACE_STATUS_RUNNING = "running"
TRACE_STATUS_COMPLETED = "completed"
TRACE_STATUS_FAILED = "failed"
TRACE_STATUS_INTERRUPTED = "interrupted"

TOOL_CALL_STATUS_RUNNING = "running"
TOOL_CALL_STATUS_SUCCESS = "success"
TOOL_CALL_STATUS_FAILED = "failed"

ENV_ENABLE_TRACING = "ENABLE_TRACING"
ENV_TRACE_RETENTION_DAYS = "TRACE_RETENTION_DAYS"
ENV_TRACE_QUERY_RATE_LIMIT_PER_MINUTE = "TRACE_QUERY_RATE_LIMIT_PER_MINUTE"
ENV_TRACE_REASONING_MAX_BYTES = "TRACE_REASONING_MAX_BYTES"
ENV_TRACE_TOOL_RESULT_MAX_BYTES = "TRACE_TOOL_RESULT_MAX_BYTES"

DEFAULT_TRACE_RETENTION_DAYS = 30
DEFAULT_TRACE_QUERY_RATE_LIMIT_PER_MINUTE = 30
DEFAULT_TRACE_REASONING_MAX_BYTES = 5 * 1024
DEFAULT_TRACE_TOOL_RESULT_MAX_BYTES = 10 * 1024

REDACTED_VALUE = "[REDACTED]"
TRUNCATED_SUFFIX = "...[truncated]"
